function importfile(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 24-Jan-2018 18:01:58

% Import the file
newData1 = load('-mat', fileToRead1);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);

% Start from two as Population is an ambiguous name and we will rename it
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end
